### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by bagder** [cpredef/predef#2]
I presume we host/provide this information under a creative commons license? We should make it clear and provide the license as well.

**Comment by a1batross** [comment]
I don't mind. CC-BY I think probably would be the best.

Though, there are so many past contributors in the readme.

**Comment by bagder** [comment]
Yes, and all contributed under a *presumed* license I would guess. The question is which...

**Comment by a1batross** [comment]
BY requires contribution. I think that's important for many past contributors.
SA actually may fit here for the same reasons.
NC/ND... I don't know, it makes this work non-free.

cc @breese what do you think about it?

**Comment by breese** [comment]
That is a difficult question because predef is reference documentation. Should its license also cover how people use the information found therein? This is to some extent covered by the copyright "Fair Use" rule, but what should apply to project that makes extensive use of the reference documentation?

My preference is a permissive license whose sole purpose is to disclaim responsibility for the correctness of the information. This is to protect contributors from being sued by users for incorrect information.

**Comment by mmuman** [comment]
If macros become longer we might want to use a more code-focused license like BSD / MIT, which is essentially CC-By.

**Comment by bagder** [comment]
BSD/MIT would be fine with me

**Comment by a1batross** [comment]
Created a new pull request, adding Creative Common Attribution 4.0.

BSD/MIT are a software licenses, but there is no software. Although there was a predef C and C++ library in SourceForge and in the future it can be re-added back but right now, it's just a documentation, provided as is.
